services:    
  fastapi:
    build: .
    container_name: keep_alert_fastapi_app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    container_name: keep_alert_postgres_db
    restart: always
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - keep_alert_pg_data:/var/lib/postgresql/data

volumes:
  keep_alert_pg_data: