"""clientPhone

Revision ID: 40569d687ef3
Revises: ace0220dc3a5
Create Date: 2025-05-06 21:36:45.917100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40569d687ef3'
down_revision: Union[str, None] = 'ace0220dc3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('clientPhone', sa.Integer(), nullable=False))
    op.drop_column('appointments', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'clientPhone')
    # ### end Alembic commands ###
