"""create users and appointments tables

Revision ID: 75423a1798ea
Revises: d9197595bf33
Create Date: 2025-04-18 16:34:19.157654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75423a1798ea'
down_revision: Union[str, None] = 'd9197595bf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('appointments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_appointments_date_time'), 'appointments', ['date_time'], unique=False)
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'])
    op.drop_column('appointments', 'client_name')
    op.drop_column('appointments', 'client_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_date_time'), table_name='appointments')
    op.drop_column('appointments', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
